### PR TITLE
Add Main file interactions

### PR DESCRIPTION
**Pull request by Wusinho**
For this part of the project, we need to add:

- Interaction with the user

- Mock the basic flow of the game

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
# Status: Changes Required,

## Hello team 😄,

**Great initiative 👏. However, there are a few things that are missing on your game workflow.**

1).  **Your game asks for player names, but there are no indications/puts related of which player's turn it is to play.**

2). **Map out a scenario where the player is being asked to choose from available moves.**

3). **Map out a scenario where the player chooses an invalid move or a move that is already taken.**

4). **provide a sketch of how the game board will look like after a player has made a move.**

5). **Map out a scenario for when a player makes a winning move.**

6). **Map out a scenario for when the game is drawn.**

7). **Since there will be some repetitive tasks until the game ends, you have to include a loop to mimic these tasks. Something like this,**

```
game_on = true

# initial instructions for player

while game_on
  # loop for each move

  if winner # and/or draw (the exact condition in this milestone is not important)
    game_on = false
  end
end
```

## Happy coding 🥂

**PS: You can reach me on slack (Rose Wanjohi).**

**Review by teekaytech — CHANGES_REQUESTED** [review]
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello team :wave:

__You've done really well in this milestone.
However, some changes are required before it can be approved. Please check my comments below and fix them as appropriate.__

**[ REQUIRED CHANGES ]**

**Note:** _In this milestone, you are supposed to only **mock** the basic flow of the game. This means **implementing a user interface that displays prompt for users (print/puts) and collects user input (gets.chomp)**. No game logic (for example checking who is a winner) is required in this milestone - instead, you can just display "The winner is X" no mater who won.__

- [x] **Your game is executable but no flow is mocked.**
- Since you're to mock the basic flow of the game, your visitor should be able to start the game and continue with the basic flows.
- Although you're not required to build this logic at this point, your visitors should be able to start the game and stop at a point. Kindly make the game playable from the command prompt.

Here's the expected basic flow of the game to be prepared when the game is executed: ([screenshot hint](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/ruby/OOP/milestone2/logic.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59565018/))

* [x] `[OPTIONAL]` game asks players for their names
* [x] `[REQUIRED]` game tells which player turn it is (without computing who the winner is)
* [x] `[REQUIRED]` game asks the player to select from available moves
* [x] `[REQUIRED]` game informs player if the selected move is invalid (without computing what an invalid move is)
* [x] `[REQUIRED]` game displays board after the player move (without computing which spots on the board are taken)
* [x] `[REQUIRED]` game informs player if the selected move is a winning move (without computing the winning move)
* [x] `[REQUIRED]` game informs player if the selected move is a draw move (without computing draw)
* [x] `[REQUIRED]` game repeats all actions for the next player's move

- I believe that most of these flow has been implemented as a single class in your main.rb script, however, you should break down this class and make the game start when executed.



* * *
**Please make the required changes and submit another review request when you are done.**

* * *

**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Review by javitocor — CHANGES_REQUESTED** [review]
# STATUS CHANGES REQUIRED 🛑 

A great effort so far, team! 👍 
However, we still need to implement some changes in order to get the project approved! 💪 
Kindly, check my comments below 👇  apply the changes  as appropriate and resubmit your project for a new code review, only when it works and meets the requirements, you should double-check the behaviour o your terminal⏩ 
Good luck! 😺 
## Mandatory changes
- You are calling a method to 'grilla' at line 37 that does not exist, and it is throwing an error, kindly fix that bug
- All the moves I try report me 'invalid move', good and bad moves, kindly fix it
- The interaction should be a little bit longer, you know in this game can only be 9 moves maximum between both players, your loop, when working, only allow the users make 2 moves, make the loop allow the users to play more rounds

**Review by PhillipUg — APPROVED** [review]
# Status: Project Approved! 🥇 
Congratulations on implementing all requirements and getting this milestone approved. :+1:

You can merge this branch into the development branch when you're ready and go on to your next milestone.
:bulb:  Do not forget to submit your project completion form after merging this branch.

All the best team,

For any assistance, you can contact me on slack as **Phillip Musiime**

**Pull request merged**
